name: docker
on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - .gitignore
  schedule: 
    - cron: "0 0 * * 6"  # run every saturday at midnight

jobs:
  bake:
    runs-on: ubuntu-latest
    env:
      LATEST: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Authenticate Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set TAG environment variable
        run: PREFIX=TAG= .github/scripts/base_image_version.sh >> $GITHUB_ENV
      - name: Build and push
        uses: docker/bake-action@v4.3.0
        with:
          targets: release
